---
- name: Create installation directory
  file:
    path: '{{ freshrss_path }}'
    state: directory
    owner: '{{ freshrss_user }}'
    group: '{{ freshrss_group }}'
    mode: 0775
- name: Get freshrss user info
  ansible.builtin.getent:
    database: passwd
    key: '{{ freshrss_user }}'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ freshrss_path }}/docker-compose.yml'
    owner: '{{ freshrss_user }}'
    group: '{{ freshrss_group }}'
    mode: 0664
- name: Copy backup_freshrss.sh
  ansible.builtin.template:
    src: backup_freshrss.sh.j2
    dest: '{{ freshrss_path }}/backup_freshrss.sh'
    owner: '{{ freshrss_user }}'
    group: '{{ freshrss_group }}'
    mode: 0775
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ freshrss_path }}'
    user: root
    hour: 4
    minute: 30
    job: 'docker compose -f {{ freshrss_path }}/docker-compose.yml down && docker compose -f {{ freshrss_path }}/docker-compose.yml pull && docker compose -f {{ freshrss_path }}/docker-compose.yml up -d'
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ freshrss_path }}'
    user: root
    hour: 1
    minute: 0
    job: '{{ freshrss_path }}/backup_freshrss.sh'
